# Data Preprocessing

In [24]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [25]:
heart_data = pd.read_csv(r"C:\Users\user\Downloads\heart.csv")
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [26]:
heart_data.shape

(303, 14)

In [27]:
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [28]:
heart_data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [29]:
heart_data['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

1 --> Defective Heart

0 --> Healthy Heart

In [30]:
heart_data.groupby('target').mean()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
target,,,,,,,,,,,,,
0,56.601449,0.826087,0.478261,134.398551,251.086957,0.159420,0.449275,139.101449,0.550725,1.585507,1.166667,1.166667,2.543478
1,52.496970,0.563636,1.375758,129.303030,242.230303,0.139394,0.593939,158.466667,0.139394,0.583030,1.593939,0.363636,2.121212

In [31]:
heart_data.apply(lambda x: x.unique())

age         [63, 37, 41, 56, 57, 44, 52, 54, 48, 49, 64, 5...
sex                                                    [1, 0]
cp                                               [3, 2, 1, 0]
trestbps    [145, 130, 120, 140, 172, 150, 110, 135, 160, ...
chol        [233, 250, 204, 236, 354, 192, 294, 263, 199, ...
fbs                                                    [1, 0]
restecg                                             [0, 1, 2]
thalach     [150, 187, 172, 178, 163, 148, 153, 173, 162, ...
exang                                                  [0, 1]
oldpeak     [2.3, 3.5, 1.4, 0.8, 0.6, 0.4, 1.3, 0.0, 0.5, ...
slope                                               [0, 2, 1]
ca                                            [0, 2, 1, 3, 4]
thal                                             [1, 2, 3, 0]
target                                                 [1, 0]
dtype: object

In [32]:
continuous_columns = heart_data.drop(columns=['sex', 'cp', 'fbs', 'exang', 'target'])
categorical_columns = heart_data[['sex', 'cp', 'fbs', 'exang', 'target']]

In [33]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
standardized_data = scaler.fit_transform(continuous_columns)
heart_data = pd.concat([pd.DataFrame(standardized_data, columns=continuous_columns.columns),categorical_columns], axis= 1)

In [34]:
heart_data.shape

(303, 14)

In [35]:
X = heart_data.drop(columns='target', axis=1)
y = heart_data['target']

In [36]:
print(X, y)

          age  trestbps      chol   restecg   thalach   oldpeak     slope  \
0    0.952197  0.763956 -0.256334 -1.005832  0.015443  1.087338 -2.274579
1   -1.915313 -0.092738  0.072199  0.898962  1.633471  2.122573 -2.274579
2   -1.474158 -0.092738 -0.816773 -1.005832  0.977514  0.310912  0.976352
3    0.180175 -0.663867 -0.198357  0.898962  1.239897 -0.206705  0.976352
4    0.290464 -0.663867  2.082050  0.898962  0.583939 -0.379244  0.976352
..        ...       ...       ...       ...       ...       ...       ...
298  0.290464  0.478391 -0.101730  0.898962 -1.165281 -0.724323 -0.649113
299 -1.033002 -1.234996  0.342756  0.898962 -0.771706  0.138373 -0.649113
300  1.503641  0.706843 -1.029353  0.898962 -0.378132  2.036303 -0.649113
301  0.290464 -0.092738 -2.227533  0.898962 -1.515125  0.138373 -0.649113
302  0.290464 -0.092738 -0.198357 -1.005832  1.064975 -0.896862 -0.649113

           ca      thal  sex  cp  fbs  exang
0   -0.714429 -2.148873    1   3    1      0
1   -0.714429 -0.512922    1   2    0      0
2   -0.714429 -0.512922    0   1    0      0
3   -0.714429 -0.512922    1   1    0      0
4   -0.714429 -0.512922    0   0    0      1
..        ...       ...  ...  ..  ...    ...
298 -0.714429  1.123029    0   0    0      1
299 -0.714429  1.123029    1   3    0      0
300  1.244593  1.123029    1   0    1      0
301  0.265082  1.123029    1   0    0      1
302  0.265082 -0.512922    0   1    0      0

[303 rows x 13 columns] 0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

# Train Test Split

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=3)

In [38]:
print(X.shape, X_train.shape, X_test.shape)

(303, 13) (242, 13) (61, 13)

In [39]:
models = [LogisticRegression(), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

In [40]:
def compare_models_train_test():
    for model in models:
        # Training the model
        model.fit(X_train, y_train)

        # Evaluating the model
        test_pred = model.predict(X_test)
        test_acc = accuracy_score(test_pred, y_test)
        print(f'Accuracy score of the model {model}: {test_acc}')

In [41]:
compare_models_train_test()

Accuracy score of the model LogisticRegression(): 0.7868852459016393
Accuracy score of the model SVC(kernel='linear'): 0.8032786885245902
Accuracy score of the model KNeighborsClassifier(): 0.7868852459016393
Accuracy score of the model RandomForestClassifier(): 0.7868852459016393

# Cross Validation

In [42]:
cv_score_lr = cross_val_score(LogisticRegression(), X, y, cv= 5)

In [43]:
print(cv_score_lr.mean())

0.8381967213114754

In [44]:
def compare_models_cv():
    for model in models:
        # Evaluating Cross Validation score
        cv_score = cross_val_score(model, X, y, cv= 5)

        print('-'*8, model, '-'*8)
        print(f'Cross Validation accuracies: {cv_score}')
        print(f'Accuracy % : {cv_score.mean().round(3) * 100}%')

In [45]:
compare_models_cv()

-------- LogisticRegression() --------
Cross Validation accuracies: [0.81967213 0.86885246 0.85245902 0.86666667 0.78333333]
Accuracy % : 83.8%
-------- SVC(kernel='linear') --------
Cross Validation accuracies: [0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
Accuracy % : 82.8%
-------- KNeighborsClassifier() --------
Cross Validation accuracies: [0.78688525 0.8852459  0.75409836 0.88333333 0.75      ]
Accuracy % : 81.2%
-------- RandomForestClassifier() --------
Cross Validation accuracies: [0.83606557 0.8852459  0.81967213 0.8        0.76666667]
Accuracy % : 82.19999999999999%