In [57]:
import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [58]:
raw_cancer_data = sklearn.datasets.load_breast_cancer()

In [59]:
print(raw_cancer_data)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]), 'frame': None, 'target_names': array(['malignant', 'benign'], dtype='<U9'), 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n', 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23'), 'filename': 'breast_cancer.csv', 'data_module': 'sklearn.datasets.data'}

In [60]:
cancer_data = pd.DataFrame(raw_cancer_data.data, columns=raw_cancer_data.feature_names)

In [61]:
cancer_data['label'] = raw_cancer_data.target

In [62]:
cancer_data.head()

   mean radius  mean texture  ...  worst fractal dimension  label
0        17.99         10.38  ...                  0.11890      0
1        20.57         17.77  ...                  0.08902      0
2        19.69         21.25  ...                  0.08758      0
3        11.42         20.38  ...                  0.17300      0
4        20.29         14.34  ...                  0.07678      0

[5 rows x 31 columns]

In [63]:
cancer_data.isnull().sum().sum()

np.int64(0)

In [64]:
cancer_data.shape

(569, 31)

In [65]:
cancer_data.describe()

       mean radius  mean texture  ...  worst fractal dimension       label
count   569.000000    569.000000  ...               569.000000  569.000000
mean     14.127292     19.289649  ...                 0.083946    0.627417
std       3.524049      4.301036  ...                 0.018061    0.483918
min       6.981000      9.710000  ...                 0.055040    0.000000
25%      11.700000     16.170000  ...                 0.071460    0.000000
50%      13.370000     18.840000  ...                 0.080040    1.000000
75%      15.780000     21.800000  ...                 0.092080    1.000000
max      28.110000     39.280000  ...                 0.207500    1.000000

[8 rows x 31 columns]

In [66]:
cancer_data['label'].value_counts()

label
1    357
0    212
Name: count, dtype: int64

1 --> Belign

0 --> Malignant

In [67]:
X = cancer_data.drop('label', axis=1)
y = cancer_data['label']

In [68]:
print(X, y)

     mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns] 0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: label, Length: 569, dtype: int64

In [69]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=2)

In [70]:
print(X.shape, X_train.shape, X_test.shape)

(569, 30) (455, 30) (114, 30)

In [71]:
#scaler = StandardScaler()
#X_train = scaler.fit_transform(X_train)
#X_test = scaler.transform(X_test)

In [72]:
model = SVC()

# Grid Search

In [73]:
# Hyperparameter tuning
parameters = {
    'kernel' : ['linear', 'poly', 'rbf', 'sigmoid'],
    'C' : [1, 5, 10, 20]
}

In [74]:
classifier = GridSearchCV(model, parameters, cv=5)

In [75]:
classifier.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 5, 10, 20],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [76]:
classifier.cv_results_

{'mean_fit_time': array([3.85836363e-01, 1.60846710e-03, 1.86676979e-03, 3.21183205e-03,
        9.25571632e-01, 2.06670761e-03, 1.91173553e-03, 2.98018456e-03,
        2.05551534e+00, 1.83849335e-03, 2.02407837e-03, 3.07283401e-03,
        1.45480690e+00, 2.04291344e-03, 1.82666779e-03, 2.84209251e-03]),
 'std_fit_time': array([1.96853822e-01, 4.75996230e-05, 6.85124567e-05, 9.02732965e-05,
        2.57105010e-01, 3.88384922e-04, 2.48545284e-04, 1.48346209e-04,
        1.82875959e+00, 5.83153324e-05, 1.74329578e-04, 1.59466038e-04,
        6.49737792e-01, 2.97264032e-04, 2.81188960e-04, 1.30230382e-04]),
 'mean_score_time': array([0.00160151, 0.00100503, 0.00134659, 0.00138783, 0.00133066,
        0.00094347, 0.00121264, 0.00135975, 0.00129991, 0.00099578,
        0.00128889, 0.00133696, 0.00125699, 0.00098104, 0.00113602,
        0.00124769]),
 'std_score_time': array([2.98914431e-04, 8.82305441e-05, 7.79880256e-05, 8.30901575e-05,
        1.65536435e-04, 3.97355588e-05, 9.90077926e-05, 1.49399360e-04,
        1.65965117e-04, 7.66210102e-05, 1.76588966e-04, 1.48662930e-04,
        8.00723607e-05, 1.14238719e-04, 5.28561461e-05, 1.38748994e-04]),
 'param_C': masked_array(data=[1, 1, 1, 1, 5, 5, 5, 5, 10, 10, 10, 10, 20, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'poly', 'rbf', 'sigmoid', 'linear', 'poly',
                    'rbf', 'sigmoid', 'linear', 'poly', 'rbf', 'sigmoid',
                    'linear', 'poly', 'rbf', 'sigmoid'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'poly'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'sigmoid'},
  {'C': 5, 'kernel': 'linear'},
  {'C': 5, 'kernel': 'poly'},
  {'C': 5, 'kernel': 'rbf'},
  {'C': 5, 'kernel': 'sigmoid'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'poly'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'sigmoid'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'poly'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'sigmoid'}],
 'split0_test_score': array([0.92307692, 0.85714286, 0.85714286, 0.41758242, 0.94505495,
        0.89010989, 0.89010989, 0.37362637, 0.93406593, 0.89010989,
        0.89010989, 0.38461538, 0.94505495, 0.89010989, 0.9010989 ,
        0.36263736]),
 'split1_test_score': array([0.93406593, 0.87912088, 0.87912088, 0.46153846, 0.95604396,
        0.86813187, 0.89010989, 0.45054945, 0.93406593, 0.86813187,
        0.89010989, 0.46153846, 0.94505495, 0.89010989, 0.89010989,
        0.46153846]),
 'split2_test_score': array([0.91208791, 0.9010989 , 0.89010989, 0.46153846, 0.92307692,
        0.92307692, 0.92307692, 0.41758242, 0.91208791, 0.91208791,
        0.91208791, 0.41758242, 0.91208791, 0.91208791, 0.91208791,
        0.38461538]),
 'split3_test_score': array([0.94505495, 0.95604396, 0.95604396, 0.40659341, 0.95604396,
        0.95604396, 0.96703297, 0.37362637, 0.95604396, 0.94505495,
        0.95604396, 0.37362637, 0.96703297, 0.95604396, 0.95604396,
        0.36263736]),
 'split4_test_score': array([0.96703297, 0.91208791, 0.91208791, 0.52747253, 0.97802198,
        0.94505495, 0.94505495, 0.47252747, 0.97802198, 0.94505495,
        0.94505495, 0.47252747, 0.97802198, 0.94505495, 0.94505495,
        0.46153846]),
 'mean_test_score': array([0.93626374, 0.9010989 , 0.8989011 , 0.45494505, 0.95164835,
        0.91648352, 0.92307692, 0.41758242, 0.94285714, 0.91208791,
        0.91868132, 0.42197802, 0.94945055, 0.91868132, 0.92087912,
        0.40659341]),
 'std_test_score': array([0.01890621, 0.03333132, 0.03361991, 0.04261697, 0.01785503,
        0.03304021, 0.03029461, 0.03992506, 0.02241327, 0.03029461,
        0.02745054, 0.03968235, 0.02262776, 0.02745054, 0.0254414 ,
        0.0455746 ]),
 'rank_test_score': array([ 4, 11, 12, 13,  1,  9,  5, 15,  3, 10,  7, 14,  2,  7,  6, 16],
       dtype=int32)}

In [77]:
best_params = classifier.best_params_
best_params

{'C': 5, 'kernel': 'linear'}

In [78]:
print(classifier.best_score_)

0.9516483516483516

In [79]:
# Loading results to DataFrame

result = pd.DataFrame(classifier.cv_results_)
result.head()

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.385836      0.196854  ...        0.018906                4
1       0.001608      0.000048  ...        0.033331               11
2       0.001867      0.000069  ...        0.033620               12
3       0.003212      0.000090  ...        0.042617               13
4       0.925572      0.257105  ...        0.017855                1

[5 rows x 15 columns]

In [80]:
result.sort_values(by='mean_test_score', ascending=False)[['params', 'mean_test_score']].reset_index(drop=True)

                            params  mean_test_score
0     {'C': 5, 'kernel': 'linear'}         0.951648
1    {'C': 20, 'kernel': 'linear'}         0.949451
2    {'C': 10, 'kernel': 'linear'}         0.942857
3     {'C': 1, 'kernel': 'linear'}         0.936264
4        {'C': 5, 'kernel': 'rbf'}         0.923077
5       {'C': 20, 'kernel': 'rbf'}         0.920879
6       {'C': 10, 'kernel': 'rbf'}         0.918681
7      {'C': 20, 'kernel': 'poly'}         0.918681
8       {'C': 5, 'kernel': 'poly'}         0.916484
9      {'C': 10, 'kernel': 'poly'}         0.912088
10      {'C': 1, 'kernel': 'poly'}         0.901099
11       {'C': 1, 'kernel': 'rbf'}         0.898901
12   {'C': 1, 'kernel': 'sigmoid'}         0.454945
13  {'C': 10, 'kernel': 'sigmoid'}         0.421978
14   {'C': 5, 'kernel': 'sigmoid'}         0.417582
15  {'C': 20, 'kernel': 'sigmoid'}         0.406593

In [81]:
grid_search_result = result[['param_C', 'param_kernel', 'mean_test_score']]

In [82]:
grid_search_result

    param_C param_kernel  mean_test_score
0         1       linear         0.936264
1         1         poly         0.901099
2         1          rbf         0.898901
3         1      sigmoid         0.454945
4         5       linear         0.951648
5         5         poly         0.916484
6         5          rbf         0.923077
7         5      sigmoid         0.417582
8        10       linear         0.942857
9        10         poly         0.912088
10       10          rbf         0.918681
11       10      sigmoid         0.421978
12       20       linear         0.949451
13       20         poly         0.918681
14       20          rbf         0.920879
15       20      sigmoid         0.406593

In [83]:
best_model = classifier.best_estimator_

In [84]:
best_model.score(X_test, y_test)

0.9649122807017544

# **Randomized Search**

In [85]:
model = SVC()

In [86]:
# Hyperparameter tuning
parameters = {
    'kernel' : ['linear', 'poly', 'rbf', 'sigmoid'],
    'C' : [1, 5, 10, 20]
}

classifier = RandomizedSearchCV(model, parameters, cv=5)

In [87]:
classifier.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [1, 5, 10, 20],
                                        'kernel': ['linear', 'poly', 'rbf',
                                                   'sigmoid']})

In [88]:
classifier.cv_results_

{'mean_fit_time': array([0.00226369, 0.00184784, 0.00309496, 0.00193658, 0.00173922,
        0.00319262, 0.00165939, 0.0016325 , 0.00289683, 1.51368451]),
 'std_fit_time': array([2.95963478e-04, 1.31296105e-04, 3.10787279e-04, 9.32915296e-05,
        1.05021086e-04, 2.91005416e-04, 1.26904456e-04, 6.19487266e-05,
        1.60948145e-04, 6.64745648e-01]),
 'mean_score_time': array([0.00148902, 0.00104079, 0.00139413, 0.00135345, 0.0011436 ,
        0.0013433 , 0.00095425, 0.0009913 , 0.0012218 , 0.00142722]),
 'std_score_time': array([1.47081239e-04, 4.05526385e-05, 2.18172703e-04, 1.48309955e-04,
        2.32037016e-05, 1.00595622e-04, 3.52500398e-05, 8.02888716e-05,
        4.81281077e-05, 2.54370184e-04]),
 'param_kernel': masked_array(data=['rbf', 'poly', 'sigmoid', 'rbf', 'rbf', 'sigmoid',
                    'poly', 'poly', 'sigmoid', 'linear'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[5, 10, 10, 1, 10, 1, 1, 5, 5, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'params': [{'kernel': 'rbf', 'C': 5},
  {'kernel': 'poly', 'C': 10},
  {'kernel': 'sigmoid', 'C': 10},
  {'kernel': 'rbf', 'C': 1},
  {'kernel': 'rbf', 'C': 10},
  {'kernel': 'sigmoid', 'C': 1},
  {'kernel': 'poly', 'C': 1},
  {'kernel': 'poly', 'C': 5},
  {'kernel': 'sigmoid', 'C': 5},
  {'kernel': 'linear', 'C': 20}],
 'split0_test_score': array([0.89010989, 0.89010989, 0.38461538, 0.85714286, 0.89010989,
        0.41758242, 0.85714286, 0.89010989, 0.37362637, 0.94505495]),
 'split1_test_score': array([0.89010989, 0.86813187, 0.46153846, 0.87912088, 0.89010989,
        0.46153846, 0.87912088, 0.86813187, 0.45054945, 0.94505495]),
 'split2_test_score': array([0.92307692, 0.91208791, 0.41758242, 0.89010989, 0.91208791,
        0.46153846, 0.9010989 , 0.92307692, 0.41758242, 0.91208791]),
 'split3_test_score': array([0.96703297, 0.94505495, 0.37362637, 0.95604396, 0.95604396,
        0.40659341, 0.95604396, 0.95604396, 0.37362637, 0.96703297]),
 'split4_test_score': array([0.94505495, 0.94505495, 0.47252747, 0.91208791, 0.94505495,
        0.52747253, 0.91208791, 0.94505495, 0.47252747, 0.97802198]),
 'mean_test_score': array([0.92307692, 0.91208791, 0.42197802, 0.8989011 , 0.91868132,
        0.45494505, 0.9010989 , 0.91648352, 0.41758242, 0.94945055]),
 'std_test_score': array([0.03029461, 0.03029461, 0.03968235, 0.03361991, 0.02745054,
        0.04261697, 0.03333132, 0.03304021, 0.03992506, 0.02262776]),
 'rank_test_score': array([ 2,  5,  9,  7,  3,  8,  6,  4, 10,  1], dtype=int32)}

In [89]:
best_params = classifier.best_params_
best_params

{'kernel': 'linear', 'C': 20}

In [90]:
print(classifier.best_score_)

0.9494505494505494

In [91]:
# Loading results to DataFrame

result = pd.DataFrame(classifier.cv_results_)
result.head()

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.002264      0.000296  ...        0.030295                2
1       0.001848      0.000131  ...        0.030295                5
2       0.003095      0.000311  ...        0.039682                9
3       0.001937      0.000093  ...        0.033620                7
4       0.001739      0.000105  ...        0.027451                3

[5 rows x 15 columns]

In [92]:
result.sort_values(by='mean_test_score', ascending=False)[['params', 'mean_test_score']].reset_index(drop=True)

                           params  mean_test_score
0   {'kernel': 'linear', 'C': 20}         0.949451
1       {'kernel': 'rbf', 'C': 5}         0.923077
2      {'kernel': 'rbf', 'C': 10}         0.918681
3      {'kernel': 'poly', 'C': 5}         0.916484
4     {'kernel': 'poly', 'C': 10}         0.912088
5      {'kernel': 'poly', 'C': 1}         0.901099
6       {'kernel': 'rbf', 'C': 1}         0.898901
7   {'kernel': 'sigmoid', 'C': 1}         0.454945
8  {'kernel': 'sigmoid', 'C': 10}         0.421978
9   {'kernel': 'sigmoid', 'C': 5}         0.417582

In [93]:
randomized_search_result = result[['param_C', 'param_kernel', 'mean_test_score']]

In [94]:
randomized_search_result

   param_C param_kernel  mean_test_score
0        5          rbf         0.923077
1       10         poly         0.912088
2       10      sigmoid         0.421978
3        1          rbf         0.898901
4       10          rbf         0.918681
5        1      sigmoid         0.454945
6        1         poly         0.901099
7        5         poly         0.916484
8        5      sigmoid         0.417582
9       20       linear         0.949451

In [95]:
best_model = classifier.best_estimator_

In [96]:
best_model.score(X_test, y_test)

0.9824561403508771